- Merge in missing changes from gkrellm-2.3.3 release - Revert gkrellm version header change, there are too many places in code/docs containing the version number, one more or less will not hurt - configure: Make configure shell script write configure.mk and move logic for compiler and linker flags into configure - configure: Also search openssl and libntlm via pkg-config and fall back to hardcoded library names for linking if not found - Makefile: Workaround environment-bugs in win32 toolchain by switching from "override CC" to a normal makefile rule for building .o from .c files

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -4,6 +4,7 @@
 # This configure is run automatically so no need to run it by hand.
 #
 # Copyright (C) 2003-2009  Bill Wilson
+set -e
 
 for i
 do
@@ -25,32 +26,40 @@ do
 	fi
 done
 
-PKG_INCLUDE=`pkg-config gtk+-2.0 --cflags`
-PKG_LIBS=`pkg-config gtk+-2.0 --libs`
-
-rm -f configure.h configure.log test test.o test.c
-
-touch configure.h
-
+GTK_CFLAGS=`pkg-config gtk+-2.0 --cflags`
+GTK_LIBS=`pkg-config gtk+-2.0 --libs`
 CC=${CC-gcc}
 
+rm -f configure.h configure.mk configure.log
+
+touch configure.h
+touch configure.mk
 exec 5>./configure.log
 
+echo "CC    : ${CC}" 1>& 5
+echo "CFLAGS: ${CFLAGS}" 1>& 5
+
 rm -f test test.exe test.o test.c
-
-
 
 if [ "$without_ssl" != "yes" ]
 then
 # echo "Checking for ssl... " 1>& 2
 echo "Checking for ssl... " 1>& 5
 
+OPENSSL_INCLUDE=`pkg-config openssl --cflags`
+OPENSSL_LIBS=`pkg-config openssl --libs`
+if [ -z "$OPENSSL_LIBS" ]
+then
+	echo "OpenSSL not found via pkg-config, using hardcoded library names" 1>& 5
+	OPENSSL_LIBS="-lssl -lcrypto"
+fi
+
 cat << EOF > test.c
 #include <openssl/ssl.h>
 
 int main()
 	{
-	SSL_METHOD	*ssl_method  = NULL;
+	const SSL_METHOD	*ssl_method  = NULL;
 
 	SSLeay_add_ssl_algorithms();
 	SSL_load_error_strings();
@@ -60,14 +69,17 @@ int main()
 	}
 EOF
 
-$CC ${CFLAGS} ${PKG_INCLUDE} -c test.c -o test.o 2>& 5
-$CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} -lssl -lcrypto 2>& 5
+$CC ${CFLAGS} ${GTK_INCLUDE} ${OPENSSL_INCLUDE} -c test.c -o test.o 2>& 5
+$CC test.o -o test ${LINK_FLAGS} ${GTK_LIBS} ${OPENSSL_LIBS} 2>& 5
 
 if [ -x ./test ] && ./test
 then
 #	echo 'Defining HAVE_SSL' 1>& 2
 	echo 'Defining HAVE_SSL' 1>& 5
 	echo '#define HAVE_SSL 1' >> configure.h
+	echo 'HAVE_SSL=1' >> configure.mk
+	echo "SSL_LIBS=${OPENSSL_LIBS}" >> configure.mk
+	echo "SSL_INCLUDE=${OPENSSL_INCLUDE}" >> configure.mk
 	without_gnutls=yes
 else
 #	echo "Not found, mail check will not have ssl support..." 1>& 2
@@ -82,6 +94,14 @@ if [ "$without_gnutls" != "yes" ]
 then
 # echo "Checking for gnutls... " 1>& 2
 echo "Checking for gnutls... " 1>& 5
+
+GNUTLS_INCLUDE=`pkg-config gnutls --cflags`
+GNUTLS_LIBS=`pkg-config gnutls --libs`
+if [ -z "$GNUTLS_LIBS" ]
+then
+	echo "GnuTLS not found via pkg-config, using hardcoded library names" 1>& 5
+	GNUTLS_LIBS="-lgnutls-openssl"
+fi
 
 cat << EOF > test.c
 #include <gnutls/openssl.h>
@@ -106,8 +126,8 @@ int main()
 	}
 EOF
 
-$CC ${CFLAGS} ${PKG_INCLUDE} -c test.c -o test.o 2>& 5
-$CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} -lgnutls-openssl 2>& 5
+${CC} ${CFLAGS} ${GTK_INCLUDE} ${GNUTLS_INCLUDE} -c test.c -o test.o 2>& 5
+${CC} test.o -o test ${LINK_FLAGS} ${GTK_LIBS} ${GNUTLS_LIBS} 2>& 5
 
 if [ -x ./test ] && ./test
 then
@@ -115,6 +135,9 @@ then
 	echo 'Defining HAVE_GNUTLS' 1>& 5
 	echo '#define HAVE_GNUTLS 1' >> configure.h
 	echo '#define HAVE_SSL 1' >> configure.h
+	echo 'HAVE_SSL=1' >> configure.mk
+	echo "SSL_LIBS=${GNUTLS_LIBS}" >> configure.mk
+	echo "SSL_INCLUDE=${GNUTLS_INCLUDE}" >> configure.mk
 else
 #	echo "Not found, mail check will not have gnutls support..." 1>& 2
 	echo "Not found, mail check will not have gnutls support..." 1>& 5
@@ -145,14 +168,17 @@ int main()
 	}
 EOF
 
-$CC ${CFLAGS} ${PKG_INCLUDE} ${PKG_NTLM_INCLUDE} -c test.c -o test.o 2>& 5
-$CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} ${PKG_NTLM_LIBS} -lntlm 2>& 5
+${CC} ${CFLAGS} ${GTK_INCLUDE} ${PKG_NTLM_INCLUDE} -c test.c -o test.o 2>& 5
+${CC} test.o -o test ${LINK_FLAGS} ${GTK_LIBS} ${PKG_NTLM_LIBS} -lntlm 2>& 5
 
 if [ -x ./test ] && ./test
 then
 #	echo 'Defining HAVE_NTLM' 1>& 2
 	echo 'Defining HAVE_NTLM' 1>& 5
 	echo '#define HAVE_NTLM 1' >> configure.h
+	echo 'HAVE_NTLM=1' >> configure.mk
+	echo "NTLM_LIBS=${PKG_NTLM_LIBS}" >> configure.mk
+	echo "NTLM_INCLUDE=${PKG_NTLM_INCLUDE}" >> configure.mk
 else
 #	echo "Not found, mail check will not have ntlm support..." 1>& 2
 	echo "Not found, mail check will not have ntlm support..." 1>& 5
@@ -191,13 +217,15 @@ int main()
 	}
 EOF
 
-$CC ${CFLAGS} ${PKG_INCLUDE} -c test.c -o test.o 2>& 5
-$CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} -lsensors 2>& 5
+${CC} ${CFLAGS} ${GTK_INCLUDE} -c test.c -o test.o 2>& 5
+${CC} test.o -o test ${LINK_FLAGS} ${GTK_LIBS} -lsensors 2>& 5
 
 if [ -x ./test ] && ./test
 then
 	echo 'Defining HAVE_LIBSENSORS' 1>& 5
 	echo '#define HAVE_LIBSENSORS 1' >> configure.h
+	echo 'HAVE_LIBSENSORS=1' >> configure.mk
+	echo 'SENSORS_LIBS="-lsensors"' >> configure.mk
 else
 	echo "Not found, sensors will not have libsensors support..." 1>& 5
 fi
