- merge in changes from gkrellm 2.3.2 snapshot (fetched 2008-09-27)

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -34,6 +34,46 @@ exec 5>./configure.log
 
 rm -f test test.exe test.o test.c
 
+
+
+if [ "$without_ssl" != "yes" ]
+then
+# echo "Checking for ssl... " 1>& 2
+echo "Checking for ssl... " 1>& 5
+
+cat << EOF > test.c
+#include <openssl/ssl.h>
+
+int main()
+	{
+	SSL_METHOD	*ssl_method  = NULL;
+
+	SSLeay_add_ssl_algorithms();
+	SSL_load_error_strings();
+	if ((ssl_method = SSLv23_client_method()) == NULL)
+		return 1;
+	return 0;
+	}
+EOF
+
+$CC ${CFLAGS} ${PKG_INCLUDE} -c test.c -o test.o 2>& 5
+$CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} -lssl -lcrypto 2>& 5
+
+if [ -x ./test ] && ./test
+then
+#	echo 'Defining HAVE_SSL' 1>& 2
+	echo 'Defining HAVE_SSL' 1>& 5
+	echo '#define HAVE_SSL 1' >> configure.h
+	without_gnutls=yes
+else
+#	echo "Not found, mail check will not have ssl support..." 1>& 2
+	echo "Not found, mail check will not have ssl support..." 1>& 5
+fi
+fi
+# end of ssl check
+
+rm -f test test.exe test.o test.c
+
 if [ "$without_gnutls" != "yes" ]
 then
 # echo "Checking for gnutls... " 1>& 2
@@ -71,51 +111,12 @@ then
 	echo 'Defining HAVE_GNUTLS' 1>& 5
 	echo '#define HAVE_GNUTLS 1' >> configure.h
 	echo '#define HAVE_SSL 1' >> configure.h
-	without_ssl=yes
 else
 #	echo "Not found, mail check will not have gnutls support..." 1>& 2
 	echo "Not found, mail check will not have gnutls support..." 1>& 5
 fi
 fi
 # end of gnutls check
-
-rm -f test test.exe test.o test.c
-
-
-if [ "$without_ssl" != "yes" ]
-then
-# echo "Checking for ssl... " 1>& 2
-echo "Checking for ssl... " 1>& 5
-
-cat << EOF > test.c
-#include <openssl/ssl.h>
-
-int main()
-	{
-	SSL_METHOD	*ssl_method  = NULL;
-
-	SSLeay_add_ssl_algorithms();
-	SSL_load_error_strings();
-	if ((ssl_method = SSLv23_client_method()) == NULL)
-		return 1;
-	return 0;
-	}
-EOF
-
-$CC ${CFLAGS} ${PKG_INCLUDE} -c test.c -o test.o 2>& 5
-$CC test.o -o test ${LINK_FLAGS} ${PKG_LIBS} -lssl -lcrypto 2>& 5
-
-if [ -x ./test ] && ./test
-then
-#	echo 'Defining HAVE_SSL' 1>& 2
-	echo 'Defining HAVE_SSL' 1>& 5
-	echo '#define HAVE_SSL 1' >> configure.h
-else
-#	echo "Not found, mail check will not have ssl support..." 1>& 2
-	echo "Not found, mail check will not have ssl support..." 1>& 5
-fi
-fi
-# end of ssl check
 
 
 rm -f test test.exe test.o test.c
@@ -130,6 +131,7 @@ cat << EOF > test.c
 
 int main()
 	{
+#if SENSORS_API_VERSION < 0x400 /* libsensors 3 code */
 	FILE	*f;
 
 	f = fopen("/etc/sensors.conf", "r");
@@ -139,6 +141,11 @@ int main()
 		return 1;
 	fclose(f);
 	return 0;
+#else /* libsensors 4 code */
+	if (sensors_init(NULL) != 0)
+		return 1;
+	return 0;
+#endif
 	}
 EOF
 
